# Generated by Django 4.2.26 on 2025-11-28 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the invoice",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        help_text="Payment gateway provider", max_length=50
                    ),
                ),
                (
                    "gateway_invoice_id",
                    models.CharField(
                        help_text="Invoice ID from the payment gateway",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount_cents",
                    models.IntegerField(help_text="Total amount in cents"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        default="draft",
                        help_text="Current status of the invoice",
                        max_length=50,
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, help_text="When the invoice was issued", null=True
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When the invoice was paid", null=True
                    ),
                ),
                (
                    "invoice_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to view/download the invoice",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the payment method",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        help_text="Payment gateway provider", max_length=50
                    ),
                ),
                (
                    "gateway_payment_method_id",
                    models.CharField(
                        help_text="Payment method ID from the gateway",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_account", "Bank Account"),
                            ("upi", "UPI"),
                            ("wallet", "Wallet"),
                        ],
                        help_text="Type of payment method",
                        max_length=50,
                    ),
                ),
                (
                    "last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of card/account number",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Card brand (Visa, Mastercard, etc.) or bank name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default payment method",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the plan",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the plan (e.g., 'Pro', 'Enterprise')",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the plan",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("razorpay", "Razorpay"),
                            ("paddle", "Paddle"),
                        ],
                        help_text="Payment gateway provider for this plan",
                        max_length=50,
                    ),
                ),
                (
                    "gateway_product_id",
                    models.CharField(
                        help_text="Product ID from the payment gateway", max_length=255
                    ),
                ),
                (
                    "gateway_price_id",
                    models.CharField(
                        help_text="Price ID from the payment gateway", max_length=255
                    ),
                ),
                (
                    "price_cents",
                    models.IntegerField(
                        help_text="Price in cents (e.g., 1999 for $19.99)"
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Yearly")],
                        default="month",
                        help_text="How often the customer is billed",
                        max_length=20,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature flags and limits for this plan",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available for new subscriptions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ["price_cents"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the subscription",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        help_text="Payment gateway provider", max_length=50
                    ),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(
                        help_text="Subscription ID from the payment gateway",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "gateway_customer_id",
                    models.CharField(
                        help_text="Customer ID from the payment gateway", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past Due"),
                            ("trialing", "Trialing"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="incomplete",
                        help_text="Current status of the subscription",
                        max_length=50,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, help_text="When the trial period ends", null=True
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the subscription will cancel at the end of the current period",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscription was cancelled",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The plan this subscription is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(
                fields=["gateway", "is_active"], name="billing_pla_gateway_ec1110_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["slug"], name="billing_pla_slug_cb45bd_idx"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that owns this payment method",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this invoice belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription this invoice is for (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["organization", "status"], name="billing_sub_organiz_e1331c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["gateway_subscription_id"],
                name="billing_sub_gateway_6d0a64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "current_period_end"],
                name="billing_sub_status_684a21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["organization", "is_default"],
                name="billing_pay_organiz_ad965b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["gateway_payment_method_id"],
                name="billing_pay_gateway_6c2dc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "status"], name="billing_inv_organiz_527da0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["gateway_invoice_id"], name="billing_inv_gateway_69a047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "issued_at"], name="billing_inv_status_2156f7_idx"
            ),
        ),
    ]
