# Generated by Django 4.2.26 on 2025-11-29 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("past_due", "Past Due"),
                    ("trialing", "Trialing"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ],
                default="incomplete",
                help_text="Current status of the subscription",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the webhook event record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique event ID from the payment gateway",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of webhook event (e.g., 'subscription.activated')",
                        max_length=100,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        help_text="Payment gateway that sent the webhook", max_length=50
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this event was processed"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Complete webhook payload for debugging"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id", "gateway"],
                        name="billing_web_event_i_583dba_idx",
                    ),
                    models.Index(
                        fields=["event_type", "gateway"],
                        name="billing_web_event_t_268c21_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="billing_web_created_f49761_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                fields=("event_id", "gateway"), name="unique_event_per_gateway"
            ),
        ),
    ]
