{
  "exclude": [
    "\\.venv/.*",
    "venv/.*",
    "saas/.*",   #add your venv name here to exclude it from the scan
    "node_modules/.*",
    "\\.pytest_cache/.*",
    "\\.ruff_cache/.*",
    ".*\\.dist-info/.*",
    ".*\\.egg-info/.*",
    "__pycache__/.*",
    "\\.git/.*",
    ".*\\.pyc$",
    ".*\\.sarif$"
  ]
}
