# Generated by Django 5.2.8 on 2025-11-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times the feature was used')),
                ('unique_users', models.IntegerField(default=0, help_text='Distinct users who used the feature')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='dailymetric',
            new_name='analytics_d_organiz_2a4001_idx',
            old_name='analytics_d_organiz_2f71a0_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='analytics_e_organiz_b90e35_idx',
            old_name='analytics_e_organiz_ae6d52_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='analytics_e_organiz_2d7c45_idx',
            old_name='analytics_e_organiz_eb8e95_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlymetric',
            new_name='analytics_m_organiz_7ebbdf_idx',
            old_name='analytics_m_organiz_4bc3a3_idx',
        ),
        migrations.AddField(
            model_name='featuremetric',
            name='organization',
            field=models.ForeignKey(help_text='Organization this metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feature_metrics', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='featuremetric',
            index=models.Index(fields=['organization', 'feature_name', 'date'], name='analytics_f_organiz_b8c85a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featuremetric',
            unique_together={('organization', 'feature_name', 'date')},
        ),
    ]
