# Generated by Django 4.2.11 on 2025-10-22 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Magic link expiration time (15 minutes from creation)",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this magic link has been used",
                        verbose_name="is used",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "magic link",
                "verbose_name_plural": "magic links",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_ma_token_83fe32_idx"),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_ma_user_id_f5f437_idx",
                    ),
                ],
            },
        ),
    ]
