# Generated by Django 4.2.11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the feature flag",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key identifier for the feature flag (e.g., 'new_dashboard', 'beta_features')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the feature flag",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this feature flag controls",
                    ),
                ),
                (
                    "default_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Default enabled state for this feature flag",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this flag belongs to. If null, this is a global flag.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="organizations.organization",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Current enabled state of the feature flag",
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object containing feature flag rules (e.g., percentage rollout, user targeting)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["organization", "key"],
                name="feature_fla_organiz_123456_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["organization", "enabled"],
                name="feature_fla_organiz_789abc_idx",
            ),
        ),
    ]
