# Generated by Django 4.2.27 on 2026-01-18 05:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="featureflag",
            new_name="feature_fla_organiz_53ddc6_idx",
            old_name="feature_fla_organiz_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="featureflag",
            new_name="feature_fla_organiz_89b366_idx",
            old_name="feature_fla_organiz_789abc_idx",
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="default_enabled",
            field=models.BooleanField(
                default=False, help_text="default enabled state for this feature flag"
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="description",
            field=models.TextField(
                blank=True, help_text="description of what this feature flag controls"
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="identifier for the feature flag",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="key",
            field=models.CharField(
                db_index=True,
                help_text="key identifier for the feature flag (e.g. new_dashboard)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="name",
            field=models.CharField(
                help_text="name for the feature flag", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object containing feature flag rules (e.g.,user targeting)",
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["key", "organization"], name="feature_fla_key_3ebae1_idx"
            ),
        ),
    ]
