# Generated by Django 4.2.27 on 2026-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "feature_flags",
            "0002_rename_feature_fla_organiz_123456_idx_feature_fla_organiz_53ddc6_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="featureflag",
            name="feature_fla_key_3ebae1_idx",
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="key",
            field=models.CharField(
                db_index=True,
                help_text="key identifier for the feature flag (e.g. new_dashboard)",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.UniqueConstraint(
                fields=("key", "organization"), name="unique_key_per_org"
            ),
        ),
    ]
